python3-scipy: Restore the numpy-include-dir fix for meson
Commit 1a05eeeb8c ("python3-scipy: fix cross-compilation errors")
added the numpy-include-dir setting to meson.cross, which
corrected builds for CPU architectures other than x86-64.

This change got lost in 9055bf850f ("python3-scipy: 1.15.1")
due to a numpy version change that made meson fail with

| ../sources/scipy-1.16.3/scipy/meson.build:87:9: ERROR:
| Include dir ../site-packages/numpy/core/include/
| does not exist.

The new numpy include directory is ../site-packages/numpy/_core/include/

Restore the previous fix with the new directory.

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>