python3-ultralytics: Remove tests directory under site-packages
This fixes a conflict:

Running transaction test
Error: Transaction test error:
  file /usr/lib/python3.14/site-packages/tests/__init__.py conflicts between attempted installs of python3-ultralytics-8.4.19-r0.corei7_64 and python3-cryptography-46.0.5-r0.corei7_64
  file /usr/lib/python3.14/site-packages/tests/__pycache__/__init__.cpython-314.pyc conflicts between attempted installs of python3-ultralytics-8.4.19-r0.corei7_64 and python3-cryptography-46.0.5-r0.corei7_64
  file /usr/lib/python3.14/site-packages/tests/__pycache__/conftest.cpython-314.pyc conflicts between attempted installs of python3-ultralytics-8.4.19-r0.corei7_64 and python3-cryptography-46.0.5-r0.corei7_64
  file /usr/lib/python3.14/site-packages/tests/conftest.py conflicts between attempted installs of python3-ultralytics-8.4.19-r0.corei7_64 and python3-cryptography-46.0.5-r0.corei7_64

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>